development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hedrasite_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hedrasite_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hedrasite_production
  pool: 5
  username: root
  password:
